export const PROPELLER_CAMPAIGN_REQUEST = "PROPELLER_CAMPAIGN_REQUEST";
export const PROPELLER_CAMPAIGN_SUCCESS = "PROPELLER_CAMPAIGN_SUCCESS";
export const PROPELLER_CAMPAIGN_FAIL = "PROPELLER_CAMPAIGN_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
