export const SMS_CAMPAIGN_REQUEST = "SMS_CAMPAIGN_REQUEST";
export const SMS_CAMPAIGN_SUCCESS = "SMS_CAMPAIGN_SUCCESS";
export const SMS_CAMPAIGN_RESET = "SMS_CAMPAIGN_RESET";
export const SMS_CAMPAIGN_FAIL = "SMS_CAMPAIGN_FAIL";

export const VIDEO_FLIER_CAMPAIGN_REQUEST = "VIDEO_FLIER_CAMPAIGN_REQUEST";
export const VIDEO_FLIER_CAMPAIGN_SUCCESS = "VIDEO_FLIER_CAMPAIGN_SUCCESS";
export const VIDEO_FLIER_CAMPAIGN_FAIL = "VIDEO_FLIER_CAMPAIGN_FAIL";
export const VIDEO_FLIER_CAMPAIGN_RESET = "VIDEO_FLIER_CAMPAIGN_RESET";

export const GET_SMS_CAMPAIGN_REQUEST = "GET_SMS_CAMPAIGN_REQUEST";
export const GET_SMS_CAMPAIGN_SUCCESS = "GET_SMS_CAMPAIGN_SUCCESS";
export const GET_SMS_CAMPAIGN_FAIL = "GET_SMS_CAMPAIGN_FAIL";

export const VIEW_FLIER_VIDEO_CAMPAIGN_REQUEST =
  "VIEW_FLIER_VIDEO_CAMPAIGN_REQUEST";
export const VIEW_FLIER_VIDEO_CAMPAIGN_SUCCESS =
  "VIEW_FLIER_VIDEO_CAMPAIGN_SUCCESS";
export const VIEW_FLIER_VIDEO_CAMPAIGN_FAIL = "VIEW_FLIER_VIDEO_CAMPAIGN_FAIL";

export const VIEW_APP_DOWNLOAD_CAMPAIGN_REQUEST =
  "VIEW_APP_DOWNLOAD_CAMPAIGN_REQUEST";
export const VIEW_APP_DOWNLOAD_CAMPAIGN_SUCCESS =
  "VIEW_APP_DOWNLOAD_CAMPAIGN_SUCCESS";
export const VIEW_APP_DOWNLOAD_CAMPAIGN_FAIL =
  "VIEW_APP_DOWNLOAD_CAMPAIGN_FAIL";

export const APP_DOWNLOAD_CAMPAIGN_REQUEST = "APP_DOWNLOAD_CAMPAIGN_REQUEST";
export const APP_DOWNLOAD_CAMPAIGN_SUCCESS = "APP_DOWNLOAD_CAMPAIGN_SUCCESS";
export const APP_DOWNLOAD_CAMPAIGN_RESET = "APP_DOWNLOAD_CAMPAIGN_RESET";
export const APP_DOWNLOAD_CAMPAIGN_FAIL = "APP_DOWNLOAD_CAMPAIGN_FAIL";

export const GET_SINGLE_CAMPAIGN_REQUEST = "GET_SINGLE_CAMPAIGN_REQUEST";
export const GET_SINGLE_CAMPAIGN_SUCCESS = "GET_SINGLE_CAMPAIGN_SUCCESS";
export const GET_SINGLE_CAMPAIGN_FAIL = "GET_SINGLE_CAMPAIGN_FAIL";
export const INFLUENCER_CAMPAIGN_REQUEST = "INFLUENCER_CAMPAIGN_REQUEST";
export const INFLUENCER_CAMPAIGN_SUCCESS = "INFLUENCER_CAMPAIGN_SUCCESS";
export const INFLUENCER_CAMPAIGN_RESET = "INFLUENCER_CAMPAIGN_RESET";
export const INFLUENCER_CAMPAIGN_FAIL = "INFLUENCER_CAMPAIGN_FAIL";

export const GET_FILTERED_CONTACT_LIST_REQUEST =
  "GET_FILTERED_CONTACT_LIST_REQUEST";
export const GET_FILTERED_CONTACT_LIST_SUCCESS =
  "GET_FILTERED_CONTACT_LIST_SUCCESS";
export const GET_FILTERED_CONTACT_LIST_FAIL = "GET_FILTERED_CONTACT_LIST_FAIL";

export const GET_ALL_CAMPAIGN_REQUEST = "GET_ALL_CAMPAIGN_REQUEST";
export const GET_ALL_CAMPAIGN_SUCCESS = "GET_ALL_CAMPAIGN_SUCCESS";
export const GET_ALL_CAMPAIGN_FAIL = "GET_ALL_CAMPAIGN_FAIL";

export const SHOW_ADS_REQUEST = "SHOW_ADS_REQUEST";
export const SHOW_ADS_SUCCESS = "SHOW_ADS_SUCCESS";
export const SHOW_ADS_FAIL = "SHOW_ADS_FAIL";
export const SHOW_ADS_RESET = "SHOW_ADS_RESET";

export const GET_ALL_INFLUENCERS_REQUEST = "GET_ALL_INFLUENCERS_REQUEST";
export const GET_ALL_INFLUENCERS_SUCCESS = "GET_ALL_INFLUENCERS_SUCCESS";
export const GET_ALL_INFLUENCERS_FAIL = "GET_ALL_INFLUENCERS_FAIL";

export const GET_DIGITAL_CAMPAIGNS_REQUEST = "GET_DIGITAL_CAMPAIGNS_REQUEST";
export const GET_DIGITAL_CAMPAIGNS_SUCCESS = "GET_DIGITAL_CAMPAIGNS_SUCCESS";
export const GET_DIGITAL_CAMPAIGNS_FAIL = "GET_DIGITAL_CAMPAIGNS_FAIL";

export const GET_ALL_INFLUENCER_CAMPAIGN_REQUEST =
  "GET_ALL_INFLUENCER_CAMPAIGN_REQUEST";
export const GET_ALL_INFLUENCER_CAMPAIGN_SUCCESS =
  "GET_ALL_INFLUENCER_CAMPAIGN_SUCCESS";
export const GET_ALL_INFLUENCER_CAMPAIGN_FAIL =
  "GET_ALL_INFLUENCER_CAMPAIGN_FAIL";

export const UPDATE_INFLUENCER_CAMPAIGN_STATUS_REQUEST =
  "UPDATE_INFLUENCER_CAMPAIGN_STATUS_REQUEST";
export const UPDATE_INFLUENCER_CAMPAIGN_STATUS_SUCCESS =
  "UPDATE_INFLUENCER_CAMPAIGN_STATUS_SUCCESS";
export const UPDATE_INFLUENCER_CAMPAIGN_STATUS_FAIL =
  "UPDATE_INFLUENCER_CAMPAIGN_STATUS_FAIL";
export const UPDATE_INFLUENCER_CAMPAIGN_STATUS_RESET =
  "UPDATE_INFLUENCER_CAMPAIGN_STATUS_RESET";

export const UPDATE_INFLUENCER_PUBLISHED_STATUS_REQUEST =
  "UPDATE_INFLUENCER_PUBLISHED_STATUS_REQUEST";
export const UPDATE_INFLUENCER_PUBLISHED_STATUS_SUCCESS =
  "UPDATE_INFLUENCER_PUBLISHED_STATUS_SUCCESS";
export const UPDATE_INFLUENCER_PUBLISHED_STATUS_FAIL =
  "UPDATE_INFLUENCER_PUBLISHED_STATUS_FAIL";
export const UPDATE_INFLUENCER_PUBLISHED_STATUS_RESET =
  "UPDATE_INFLUENCER_PUBLISHED_STATUS_RESET";

export const GET_INFLUENCER_DETAILS_REQUEST = "GET_INFLUENCER_DETAILS_REQUEST";
export const GET_INFLUENCER_DETAILS_SUCCESS = "GET_INFLUENCER_DETAILS_SUCCESS";
export const GET_INFLUENCER_DETAILS_FAIL = "GET_INFLUENCER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
