export const SMS_CAMPAIGN_REQUEST = 'SMS_CAMPAIGN_REQUEST'
export const SMS_CAMPAIGN_SUCCESS = 'SMS_CAMPAIGN_SUCCESS'
export const SMS_CAMPAIGN_RESET = 'SMS_CAMPAIGN_RESET'
export const SMS_CAMPAIGN_FAIL = 'SMS_CAMPAIGN_FAIL'
export const GET_ALL_CAMPAIGN_REQUEST = 'GET_ALL_CAMPAIGN_REQUEST'
export const GET_ALL_CAMPAIGN_SUCCESS = 'GET_ALL_CAMPAIGN_SUCCESS'
export const GET_ALL_CAMPAIGN_FAIL = 'GET_ALL_CAMPAIGN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'