export const CAMPAIGN_TOTAL_REQUEST = "CAMPAIGN_TOTAL_REQUEST";
export const CAMPAIGN_TOTAL_SUCCESS = "CAMPAIGN_TOTAL_SUCCESS";
export const CAMPAIGN_TOTAL_FAIL = "CAMPAIGN_TOTAL_FAIL";

export const COST_TOTAL_REQUEST = "COST_TOTAL_REQUEST";
export const COST_TOTAL_SUCCESS = "COST_TOTAL_SUCCESS";
export const COST_TOTAL_FAIL = "COST_TOTAL_FAIL";
