export const GET_SENDERID_REQUEST = "GET_SENDERID_REQUEST";
export const GET_SENDERID_SUCCESS = "GET_SENDERID_SUCCESS";
export const GET_SENDERID_FAIL = "GET_SENDERID_FAIL";

export const CREATE_SENDERID_REQUEST = "CREATE_SENDERID_REQUEST";
export const CREATE_SENDERID_SUCCESS = "CREATE_SENDERID_SUCCESS";
export const CREATE_SENDERID_RESET = "CREATE_SENDERID_RESET";
export const CREATE_SENDERID_FAIL = "CREATE_SENDERID_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
